### ISSUE TITLE
设置日历的问题

### ISSUE THREAD

**Issue by nobrokenboy** [lerhxx/vue-datepicker#1]
请问如何让这个日历可以选中当天前的其他日期

**Comment by lerhxx** [comment]
<caleendar isAbandon=false></caleendar>

**Comment by lerhxx** [comment]
<caleendar isAbandon=false></caleendar>

**Comment by lerhxx** [comment]
"<caleendar isAbandon=false></caleendar>"

**Comment by lerhxx** [comment]
isAbandon设置为false，就可以了
